[build]
# 将编译输出目录设置为项目根目录下的 exe-location
target-dir = "../../exe-location/target"

[target.aarch64-linux-android]
linker = "E:/@imFile-Download/AndroidSdk/ndk/29.0.13846066/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android24-clang.cmd"
ar = "E:/@imFile-Download/AndroidSdk/ndk/29.0.13846066/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"

[target.armv7-linux-androideabi]
linker = "E:/@imFile-Download/AndroidSdk/ndk/29.0.13846066/toolchains/llvm/prebuilt/windows-x86_64/bin/armv7a-linux-androideabi24-clang.cmd"
ar = "E:/@imFile-Download/AndroidSdk/ndk/29.0.13846066/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"

[target.i686-linux-android]
linker = "E:/@imFile-Download/AndroidSdk/ndk/29.0.13846066/toolchains/llvm/prebuilt/windows-x86_64/bin/i686-linux-android24-clang.cmd"
ar = "E:/@imFile-Download/AndroidSdk/ndk/29.0.13846066/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"

[target.x86_64-linux-android]
linker = "E:/@imFile-Download/AndroidSdk/ndk/29.0.13846066/toolchains/llvm/prebuilt/windows-x86_64/bin/x86_64-linux-android24-clang.cmd"
ar = "E:/@imFile-Download/AndroidSdk/ndk/29.0.13846066/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"
